[package]
name = "prost"
# NB: When modifying, also modify html_root_url in lib.rs
version = "0.2.3"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "Apache-2.0"
repository = "https://github.com/danburkert/prost"
documentation = "https://docs.rs/prost"
readme = "README.md"
description = "A Protocol Buffers implementation for the Rust Language."
keywords = ["protobuf", "serialization"]
categories = ["encoding"]

[badges]
travis-ci = { repository = "danburkert/prost" }
appveyor = { repository = "danburkert/prost" }

[workspace]
members = [
  "benchmarks",
  "conformance",
  "prost-build",
  "prost-derive",
  "prost-types",
  "protobuf",
  "tests",
]
exclude = [
  # The fuzz crate can't be compiled or tested without the 'cargo fuzz' command,
  # so exclude it from normal builds.
  "fuzz",
]

[dependencies]
byteorder = "1"
bytes = "0.4"

[dev-dependencies]
env_logger = "0.4"
log = "0.3"
prost-derive = { version = "0.2", path = "prost-derive" }
quickcheck = "0.4"

[features]
default = ["std"]
std = []
